Settings:
  defaultLanguage: EN
  availableLanguages:
  minimumHorsenameLength: 0
  maximumHorsenameLength: 30
  muteConsole: false
  worldCrossing: true
  claimOnTame: false
  lockOnClaim: false
  protectOnClaim: false
ActiveWorlds:
Economy:
Horsenames:
- Arod
- Ashufel
- Grispoil
- Pegase
- Ponyta
- Thunderstorm
- Tonnerre
- Tornado
Groups:
  default:
    color: <f>
    maximumClaims: 0
    permission: zh.group.default
  player:
    color: <dark_aqua>
    maximumClaims: 5
    permission: zh.whateveryouwant
  vip:
    color: <BOLD>
    maximumClaims: 10
  admin:
    color: §c
    maximumClaims: -1
