settings:
  default-language: EN
  minimum-horsename-length: 0
  maximum-horsename-length: 30
  mute-console: false
  active-worlds:
economy:
horsenames:
- Arod
- Ashufel
- Grispoil
- Pegase
- Ponyta
- Tonnerre
- Tornado
groups:
  default:
    color: WHITE
    maximum-claims: 0
  users:
    color: AQUA
    maximum-claims: 1
  vip:
    color: MAGIC
    maximum-claims: 10
  admin:
    color: RED
    maximum-claims: -1