Settings:
  defaultLanguage: EN
  availableLanguages:
  minimumHorsenameLength: 0
  maximumHorsenameLength: 30
  muteConsole: false
  worldCrossing: true
  claimOnTame: false
  activeWorlds:
Economy:
Horsenames:
- Arod
- Ashufel
- Grispoil
- Pegase
- Ponyta
- Thunderstorm
- Tonnerre
- Tornado
Groups:
  default:
    color: <white>
    maximumClaims: 0
    permission: zh.group.default
  player:
    color: dark_aqua
    maximumClaims: 5
    permission: zh.whateveryouwant
  vip1:
    color: BOLD
    maximumClaims: 10
  vip2:
    color: <ITALIC>
    maximumClaims: 15
  admin:
    color: <c>
    maximumClaims: -1
