Settings:
  defaultLanguage: EN
  availableLanguages:
  minimumHorsenameLength: 0
  maximumHorsenameLength: 30
  muteConsole: false
  worldCrossing: true
  activeWorlds:
Economy:
Horsenames:
- Arod
- Ashufel
- Grispoil
- Pegase
- Ponyta
- Thunderstorm
- Tonnerre
- Tornado
#test
Groups:
  default:
    color: <white>
    maximumClaims: 0
  player:
    color: dark_aqua
    maximumClaims: 5
  vip:
    color: BOLD
    maximumClaims: 10
  admin:
    color: <c>
    maximumClaims: -1
